group=com.github.ssquadteam
version=1.0.0

org.gradle.jvmargs=-Xmx900m -Xms128m -XX:MaxMetaspaceSize=384m
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.vfs.watch=false
org.gradle.daemon.idletimeout=600000
kotlin.daemon.jvmargs=-Xmx700m
kotlin.compiler.execution.strategy=in-process
